# Generated by Django 3.2.8 on 2021-10-16 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audiobook',
            old_name='dueration',
            new_name='duration',
        ),
        migrations.RenameField(
            model_name='podcast',
            old_name='dueration',
            new_name='duration',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='dueration',
            new_name='duration',
        ),
    ]
